# Generated by Django 6.1.1 on 2026-10-05 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0001_initial'),
    ]

    operations = [
    ]
