# Generated by Django 6.1.1 on 2026-10-05 21:49

from django.db import migrations

EXCHANGE_SQL = """
INSERT INTO exchange_exchangeprogram (university, languages, places, deadline, description)
VALUES 
    ('Uniwersytet Warszawski, Польща', 'польська, англійська', '5', '2026-11-15', 'Найбільший університет Польщі. Студенти обміну можуть обирати курси з економіки польською або англійською мовою.'),
    ('KU Leuven (Бельгія)', 'English', '2 місця', '2026-12-01', 'Один з найстаріших університетів Європи, заснований у 1425 році. Семестр на факультеті економіки та бізнесу англійською мовою.'),
    ('Vilnius University, Литва', 'англійська', 'до 4', '2026-10-20', 'Найстаріший університет Литви, заснований у 1579 році. Школа бізнесу пропонує курси з економіки та фінансів англійською.'),
    ('Uniwersytet Jagielloński, Польща', 'Польська, Англійська', '3', '2026-11-15', 'Найстаріший університет Польщі, заснований у 1364 році в Кракові. Студенти обирають курси з економіки та менеджменту.'),
    ('University of Tartu - Естонія', 'англійська, естонська', '2', '2027-01-10', 'Провідний університет Естонії, заснований у 1632 році. Школа економіки та бізнес-адміністрування пропонує семестрові курси англійською.'),
    ('Masaryk University, Чехія', 'англійська', '1 місце', '2026-09-30', 'Другий за величиною університет Чехії, розташований у Брно. Факультет економіки та адміністрування приймає студентів обміну на семестр.');
"""
REVERSE_SQL = "DELETE FROM exchange_exchangeprogram WHERE university IN('Uniwersytet Warszawski, Польща','KU Leuven (Бельгія)','Vilnius University, Литва','Uniwersytet Jagielloński, Польща','University of Tartu - Естонія','Masaryk University, Чехія');"

class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(EXCHANGE_SQL, reverse_sql=REVERSE_SQL),
    ]
