# Generated by Django 6.1.1 on 2026-10-05 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0002_import_programs'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangeprogram',
            name='country',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='exchangeprogram',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
