# Generated by Django 6.1.1 on 2026-10-05 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0004_split_university'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchangeprogram',
            name='university',
        ),
        migrations.AlterField(
            model_name='exchangeprogram',
            name='country',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='exchangeprogram',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
