# Generated by Django 6.1.1 on 2026-10-05 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0005_remove_exchangeprogram_university_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangeprogram',
            name='places_count',
            field=models.IntegerField(null=True),
        ),
    ]
