# Generated by Django 6.1.1 on 2026-10-06 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0007_convert_places'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchangeprogram',
            name='places',
        ),
        migrations.AlterField(
            model_name='exchangeprogram',
            name='places_count',
            field=models.IntegerField(),
        ),
    ]
