# Generated by Django 6.1.1 on 2026-10-06 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0008_remove_exchangeprogram_places_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exchangeprogram',
            old_name='places_count',
            new_name='places',
        ),
    ]
